image: iquiw/alpine-emacs
before_script:
  - apk update && apk add make

stages:
  - publish

.publish: &publish
  script:
  - make publish
  artifacts:
    paths:
    - public

pages:
  stage: publish
  <<: *publish
  only:
  - master

pages:preview:
  stage: publish
  <<: *publish
  except:
  - master
