#+TITLE: Change the gVim menu language
#+REDIRECT_FROM: /2009/05/06/changing-gvim-menu-language/
#+DATE: <2009-05-06 Wed>

** Problem
   :PROPERTIES:
   :CUSTOM_ID: problem
   :ID:       cb66bb1f-3c18-4dc7-9202-7f5ca0ce88ed
   :END:

I wanted to try gVim (Vim on Windows with a GUI) on my Vista
machine. So I've downloaded the [[http://www.vim.org/download.php#pc][installer]] from the [[http://www.vim.org/][website]] and ran
it. Everything OK so far. But when I started it, it seems the menu's
are in Dutch. I *really* hate that, because I use all software in
English (and the Dutch translations in gVim, as in many other apps,
really suck). But it took me some time to find out how to change
it. But I've found a way.

** Solution
   :PROPERTIES:
   :CUSTOM_ID: solution
   :ID:       dd90ce54-bb98-4cbb-8f68-b38d2ee0fa33
   :END:

Add the following lines at the top of the file
=%PROGRAM_FILES%/Vim/_vimrc=.

#+BEGIN_SRC vim
    lang en
    language mes en
    set langmenu=en_US.UTF-8
#+END_SRC

That's it, just restart and everything should be in English.

** Additional:
   :PROPERTIES:
   :CUSTOM_ID: additional
   :ID:       a4a1d15e-de05-4c6a-902b-aec2f7cab8e4
   :END:

To modify the window size, add:

#+BEGIN_SRC vim
    winsize 200 50
#+END_SRC

Enjoy your Vimming...
