#+TITLE: First days with the Truly Ergonomic keyboard
#+REDIRECT_FROM: /2013/03/12/first-hours-with-the-truly-ergonomic-keyboard/
#+DATE: <2013-03-12 Tue>

** First feel
   :PROPERTIES:
   :CUSTOM_ID: first-feel
   :ID:       2676323c-27de-4568-9bc0-aa38139388ac
   :END:

Yesterday I received my [[http://www.trulyergonomic.com/store/index.php?route=product/category&path=78#Model-207][Truly Ergonomic]] keyboard. At first, it feels
really awkward. It's like I have to learn how to type all over
again. I am constantly looking at the keyboard to locate the keys.

** Ctrl & Shift
   :PROPERTIES:
   :CUSTOM_ID: ctrl-shift
   :ID:       058b02f1-8794-4785-bd8a-1957a75672e4
   :END:

I am a heavy emacs user, so I constantly use ~Ctrl~. Therefore I had
~Caps Lock~ remapped to ~Ctrl~. But now with the Truly Ergonomic it
feels like the ~Ctrl~ & ~Shift~ are swapped. So I started to wonder
"How to remap keys?". Fortunately Truly Ergonomic provides an [[http://www.trulyergonomic.com/store/index.php?route=product/category&path=79_90#Ctrl_Shift][official
firmware]] that will swap these keys.

** Alt/Meta
   :PROPERTIES:
   :CUSTOM_ID: altmeta
   :ID:       95c452d2-7c1f-454f-ba3d-e8f3f042a8ab
   :END:

This is something I was afraid for. The default location of ~Alt~ is
all the way at the bottom corners. For an emacs user this is a
disaster. So people [[https://twitter.com/xah_lee/status/308865952584458240][suggested]] me to remap the left ~Space~ to ~Alt~,
and I've tried this for a while (in a later post I'll share
how). Result: Alt is easily accessible, but I can no longer type a
Space with my left hand. And it will be hard to lose of this habit...

** Mac
   :PROPERTIES:
   :CUSTOM_ID: mac
   :ID:       78501e09-c23e-47cc-ae0d-37140769f506
   :END:

I work on 3 different operating systems: Mac (at home), Windows and
Linux (at work). Meanwhile I'm already used to switching, so I like
the ~Ctrl~ on the same location for all systems. That's why I didn't
set [[http://www.trulyergonomic.com/store/index.php?route=product/category&path=79_80#DIP][toggle DIP switch #2]]. But this means the ~SuperKey~, at the center
of the keyboard, is the only ~⌘~ key. This key is located between the
~5~ and ~6~. And this does not feel right. But I'm not sure yet how to
fix this problem?

** Tab, Backspace & ENTER
   :PROPERTIES:
   :CUSTOM_ID: tab-backspace-enter
   :ID:       1e072a09-fa3a-4a0f-81f5-d48961c18074
   :END:

It would take so me time to learn their location, but I'm pretty sure
I'll get used to these quickly.

** Key arrangement
   :PROPERTIES:
   :CUSTOM_ID: key-arrangement
   :ID:       0b5b6203-d449-45fe-85d5-5f68b9bb4c08
   :END:

It also will require some practice, more than expected. I've noticed
it is important to use the correct finger for each key (so I'll have
to use my pinkies). But I'm sure it will pay of at the end.

** Mechanical keys
   :PROPERTIES:
   :CUSTOM_ID: mechanical-keys
   :ID:       f1f454c0-0cea-499b-a441-2da28fce33d8
   :END:

The keys are great! The required pressure is good and the sound they
make is gentle but provides a decent feedback.

** Overall
   :PROPERTIES:
   :CUSTOM_ID: overall
   :ID:       981e52af-6f0f-4c06-b049-df51ece81e72
   :END:

I try to use my keyboard for everything, but at the moment I'm grabbing
my mouse faster than before. I hope that feeling changes soon...
